### ISSUE TITLE
Detalles

### ISSUE THREAD

**Issue by memiux** [krrrunch/ccij#10]
- [x] Post destacados `featured=1, sort=featured_order,created`
- [x] Use internal `status` instead of `post_status`
- [x] Botones sociales
- [x] Mostrar CCIJ siempre como autor de la página
- [x] Corregir maquetado login
- [x] Implementar login
- [x] Que no se muestren los errores
- [x] Implementar vista de contacto
- [x] Lista de prensa y eventos
- [x] Paginado en prensa y eventos (mostrar 8 publicaciones)
- [x] Traducir todo al español
- [x] Implementar plantilla patrocinadores
- [x] El menú en móvil no coincide con el de desktop (le faltan items)
- [x] Agregar favicon
- [x] Definir correo de contacto

**Comment by jesaa** [comment]
Queda pendiente a que correo se va mandar, y con que formato.
