### ISSUE TITLE
Video en home

### ISSUE THREAD

**Issue by alero0d** [krrrunch/ccij#11]
- [x] Implementar el mismo diseño que TPSP en abajo del banner informativo y arriba de patrocinios.

- [x] El párrafo de lado debe decir: 
Somos un Consejo de Cámaras con fortaleza y dinamismo, que represente la voz de los industriales ante el gobierno y la sociedad, generando valor para sus miembros y a Jalisco, nuestro Estado.

**Comment by memiux** [comment]
Esto tiene que quedar para la [milestone v1](https://github.com/krrrunch/ccij/milestone/1) también?

**Comment by jesaa** [comment]
Falta definir video y la imagen que se utilizaran
