### ISSUE TITLE
No sirve eventos

### ISSUE THREAD

**Issue by alero0d** [krrrunch/ccij#22]
- [x] Da de alta eventos con la vista de noticias.

- [x] No carga patrocinadores en la vista de noticias.

- [x] El administrador no puede dar de alta logos de patrocionadores.

**Comment by memiux** [comment]
El _administrador_ es el mismo que el editor?

/cc: @mikemotion @alero0d

**Comment by alero0d** [comment]
Sí

**Comment by alero0d** [comment]
@memiux yes!
