### ISSUE TITLE
Generar template de Publicaciones

### ISSUE THREAD

**Issue by mikemotion** [krrrunch/ccij#3]
### Publicaciones ###
* Título
* Subtitulo
* Portada (Foto)
* Pie de foto
* Contenido (Puede incluir texto / fotos / vídeos de Youtube / etc...)

**Categoría**
* Se elige una categoría de una lista de categorías

**Estatus**
* Publicado
* Borrador

**Visibilidad**
* Público
* Privado (Sólo miembros)

**Comment by memiux** [comment]
Las páginas en ProcessWire ya traen el campo `status`.

https://processwire.com/api/ref/page/#pw-methods-status
http://cheatsheet.processwire.com/page/page-status/
